### ISSUE TITLE
Button zum Seite bearbeiten: schwer erreichbar

### ISSUE THREAD

**Issue by mathContao** [xprojects-de/alpdesk-frontendediting#19]
Vielen Dank für diese sehr interessante Erweiterung.

Beim Ausprobieren ist mir aufgefallen, dass die Seiten ("Page") Buttons nur schwer erreichbar sind:
- es muss die Contao-FE-Toolbar minimiert werden, damit "page" sichtbar ist (versteckt sich dahinter)
- wenn man vom Contao-Logo nach links auf "Page" mit der Maus rutschen möchte, dann muss man den Cursor sehr schnell dahin bewegen, sonst kommt "Artikel".

Eine kurze Aufnahme:

![page-bearbeiten](https://user-images.githubusercontent.com/1645099/102884719-69533580-4452-11eb-9006-be51d33ea079.gif)

**Comment by xprojects-de** [comment]
Danke für das Feeback! Jip ist richtig! Ich hatte es immer nur mit einer Navigation als Module im Header getestet!
Diesen Fall habe ich nicht beachtet... :-) Wird gefixed!

**Comment by xprojects-de** [comment]
V 1.0.9
