### ISSUE TITLE
Icon für aktualisieren = Auge?

### ISSUE THREAD

**Issue by mathContao** [xprojects-de/alpdesk-frontendediting#21]
Für das Aktualisieren (Reload?) der Seite ist aus meiner Sicht das Auge-Icon nicht passend.

![grafik](https://user-images.githubusercontent.com/1645099/103012179-78fa7900-453b-11eb-842d-db2f67bc76a8.png)

**Comment by xprojects-de** [comment]
fixed im Zuge von 1.0.10
