### ISSUE TITLE
Icons: Artikel bearbeiten

### ISSUE THREAD

**Issue by mathContao** [xprojects-de/alpdesk-frontendediting#22]
Die Bearbeiten-Icons für Artikel sind nicht Contao-konform.

![grafik](https://user-images.githubusercontent.com/1645099/103012770-5ae14880-453c-11eb-8646-285e09233c6b.png)

![grafik](https://user-images.githubusercontent.com/1645099/103012806-6896ce00-453c-11eb-8e9c-382a10f4f52b.png)
müsste eigentlich sein:
![grafik](https://user-images.githubusercontent.com/1645099/103012854-7ba99e00-453c-11eb-87b0-f70aba4cf7bf.png)

und

![grafik](https://user-images.githubusercontent.com/1645099/103012875-82381580-453c-11eb-8b06-2723836616e5.png)
müsste eigentlich sein:
![grafik](https://user-images.githubusercontent.com/1645099/103012895-8bc17d80-453c-11eb-8733-295155507659.png)

siehe:
![grafik](https://user-images.githubusercontent.com/1645099/103012948-a136a780-453c-11eb-8f47-f902a8c387cd.png)

**Comment by xprojects-de** [comment]
fixed im Zuge von 1.0.10
