### ISSUE TITLE
Auflösung der Ansicht-Modi

### ISSUE THREAD

**Issue by mathContao** [xprojects-de/alpdesk-frontendediting#23]
Es wäre sehr hilfreich, wenn zu dem Ansichtsmodus die Pixel-Maße (Auflösung) angegeben werden, damit man das gut Einschätzen kann
![grafik](https://user-images.githubusercontent.com/1645099/103013947-4900a500-453e-11eb-8cc9-6d2e7c7b01d1.png)

**Comment by xprojects-de** [comment]
fixed im Zuge von 1.0.10
