### ISSUE TITLE
Icon Auflistung Artikel-Inhalt

### ISSUE THREAD

**Issue by mathContao** [xprojects-de/alpdesk-frontendediting#24]
![grafik](https://user-images.githubusercontent.com/1645099/103014876-caa50280-453f-11eb-95b9-f3c810a95b0b.png)

Das Icon öffnet die Liste der Inhaltselemente des Artikels.

Ich würde das Icon lieber rechts oben bei Artikel erwarten und hinter diesem Icon
![grafik](https://user-images.githubusercontent.com/1645099/103015004-fb853780-453f-11eb-99b8-b8d1615e11ac.png)
verlinken

**Comment by xprojects-de** [comment]
fixed im Zuge von 1.0.10
