### ISSUE TITLE
Element anlegen

### ISSUE THREAD

**Issue by mathContao** [xprojects-de/alpdesk-frontendediting#25]
Beim Element anlegen würde ich das Formular an 2 Stellen anpassen:
![grafik](https://user-images.githubusercontent.com/1645099/103016129-e14c5900-4541-11eb-8284-0e3f2dfc44e2.png)

Titel: "Frontend-View" => "Element anlegen"

Buttons: neben dem Speichern-Button wäre ein Button "Speichern und Schließen" sehr hilfreich

**Comment by xprojects-de** [comment]
Derzeit noch offen, aber machbar und sinnvoll.

**Comment by xprojects-de** [comment]
Wird auch in 1.1 mit Angular implementiert
#49

**Comment by xprojects-de** [comment]
.. verschoben auf 2.0.0 oder vielleicht 1.1.X

**Comment by xprojects-de** [comment]
V 1.1.1 has saveNClose and Header was completly removed
