### ISSUE TITLE
Modul "Navigation" bearbeiten: Icon und Funktion

### ISSUE THREAD

**Issue by mathContao** [xprojects-de/alpdesk-frontendediting#26]
Wenn das Modul "Navigation" bearbeitet wird:
![grafik](https://user-images.githubusercontent.com/1645099/103017545-0fcb3380-4544-11eb-83c0-6915e40cf56f.png)

Dann passt das Icon aus meiner Sicht nicht so richtig. Bei "bearbeiten" würde ich immer auf die Stift-Symbolik zurückgreifen.

Klicke ich auf das Icon, dann öffnet sich bei mir nur der Seitenbaum, jedoch nicht das Bearbeiten-Formular

**Comment by xprojects-de** [comment]
ja grundsätzlich schon, aber ich dachte mir dass alles was mit der Seitenstruktur zu tun hat auch dieses Icon haben sollte!
