### ISSUE TITLE
Template: html5 oder Twig?

### ISSUE THREAD

**Issue by mathContao** [xprojects-de/alpdesk-frontendediting#46]
Im Template-Ordner sehe ich, dass html5-Dateien verwendet werden.

Wenn ich das richtig verstanden habe, wird Contao Stück für Stück von den HTML5 zu Twig-Templates umgestellt.
(Ich meine sogar, irgendwo gelesen zu haben, dass das Backend (ziemlich) vollständig bereits auf Twig umgestellt sei. Kann mich aber auch irren)

Wäre es eventuell sinnvoll bereits jetzt schon Twig zu nutzen?

Im Handbuch gibt es Infos dazu:
https://docs.contao.org/dev/guides/back-end-routes/

**Comment by xprojects-de** [comment]
Danke für den Hinweis! Ist für die V2 geplant (wenn der Contaostandard es zwingend fordert!).
Derzeit arbeite ich noch mit einem Callback für das BackendRendering. Das wird aktuell noch als Standard definiert.

https://docs.contao.org/dev/framework/back-end-modules/

Wenn sich hier in Zukunft was tut werde ich das umstellen :-)
Aber erstmal stehen Bugfixes und andere Features im Vordergrund!

**Comment by xprojects-de** [comment]
Done V 1.2.0
