### ISSUE TITLE
Schließenbutton

### ISSUE THREAD

**Issue by mathContao** [xprojects-de/alpdesk-frontendediting#62]
gehört der nicht oben hin?

![grafik](https://user-images.githubusercontent.com/1645099/105758052-20aa0300-5f4f-11eb-9c4a-d5031f2f3806.png)

**Comment by xprojects-de** [comment]
ja normalerweise ist der beim ContaoModal oben, aber augrund der Usability und auf Rückmeldung der Kunden wurde er unten gewünscht. WIederum Ansichtssache :-)
Up for discussion...

**Comment by mathContao** [comment]
Es bricht mit dem UI und den anderen Fenstern in Contao.
Ich würde den X-Button lieber wieder oben sehen.
Alternativ könnte unten noch ein Button mit "schließen" stehen.

**Comment by xprojects-de** [comment]
fixed in v 1.2.1
