### ISSUE TITLE
Modul Navigation bearbeiten: öffnet Seitenstruktur

### ISSUE THREAD

**Issue by math-GH** [xprojects-de/alpdesk-frontendediting#63]
Wenn man das Modul "Navigation" bearbeiten will, dann öffnet sich die Seitenstruktur.

Das ist nicht das was ich unter "Modul bearbeiten" erwarte.

![grafik](https://user-images.githubusercontent.com/1645099/106055246-6b618180-60ed-11eb-8923-e06f0000f949.png)
![grafik](https://user-images.githubusercontent.com/1645099/106055261-6ef50880-60ed-11eb-94c7-2a1588bc423e.png)

**Comment by xprojects-de** [comment]
ja das ist im Moment so gewollt. :-)
Es wäre technisch kein Problem das Modul anzuzeigen nur halte ich es für nicht Sinnvoll dass der Redakteur hier das Modul sieht! Es will ja hier nach meiner Sicht einen einen neuen Menüpunkt anlegen und das muss er halt in der Seitenstruktur machen...
Up for discussion...
