### ISSUE TITLE
C 4.12.5 Aufruf von "Seite auswählen" führt zu Fehler

### ISSUE THREAD

**Issue by herrrilke** [xprojects-de/alpdesk-frontendediting#82]
In alpdesk/alpdesk-frontendediting 1.2.5 führt der Aufruf (Anklicken) von "Seite auswählen" zu diesem Fehler:

`You have requested a non-existent service "contao.routing.url_generator". Did you mean this: "contao.slug.generator"?`

sonst: alles tiptop.
Wird es für die Erweiterung noch Updates geben?

Danke und viele Grüße

**Comment by xprojects-de** [comment]
Hallo @herrrilke,

danke für den Hinweis. Welche Contao-Version benutzt du?

Ja die Erweiterung würde ich schon gerne weiter pflegen :-) Unter 4.13 sollte die 1.2.5 auf jeden Fall laufen und was in 5.0 kommt sehen wir dann. Aber wird weitergepflegt.

Grüße

**Comment by herrrilke** [comment]
hallo @xprojects-de 

freut mich zu hören!
contao-version ist  4.12.5

beste grüße

**Comment by xprojects-de** [comment]
Hi @herrrilke,

Ich denke es liegt daran dass du in der config.yaml das legacy_routing: false gesetzt hast.
Damit konnte das FEE noch nicht umgehen.

Magst du mal den 1.2.6-RC2 im Contao-Manager installieren und testen ob es dann funktioniert? Wäre super!
Habe intern auch noch ein bisschen was angepasst. Falls die noch was auffällt dann einfach melden :-) 

![Bildschirmfoto 2022-02-03 um 21 26 43](https://user-images.githubusercontent.com/55982921/152424071-da98ed6d-4403-4e9b-bdff-cb4f694f2f23.png)


Danke

**Comment by herrrilke** [comment]
hallo @xprojects-de,

du hast recht: legacy_routing habe ich auf "false" gesetzt.
mit der neuen  1.2.6-RC2 ist das problem "Seite auswählen" aber behoben! perfekt!

super gemacht! 
danke für deine schnelle reaktion!

schönes wochenende

**Comment by xprojects-de** [comment]
super danke!
1.2.6 ist released! Du kannst jetzt im CM wieder ^1.2 eintragen. Dann bekommst du wieder die releasten Versionen.

Danke für dein Feedback und jederzeit wieder wenn du Bugs oder IDeen hast :-) 

Grüße
