### ISSUE TITLE
Frontendediting für Admins Möglichkeit zur Deaktivierung

### ISSUE THREAD

**Issue by theDyingMountain** [xprojects-de/alpdesk-frontendediting#88]
Da das Modul HTML und CSS Styles einfügt, verursacht das manchmal fehlerhafte Anzeigen. Es wäre daher nützlich eine Möglichkeit zu schaffen, dass Modul auch für Admins bzw. Entwickler zu deaktivieren.

**Comment by xprojects-de** [comment]
Schöne Idee. Habe ich in der RC auch gleich umgesetzt! Der Admin hat jetzt unter "Benutzer" die Option!
See and test https://github.com/xprojects-de/alpdesk-frontendediting/releases/tag/1.3.0-RC0

Thanks :-)

**Comment by theDyingMountain** [comment]
Danke für die schnelle Umsetzung. Ich bekomme jedoch folgende Fehlermeldung `Cannot assign string to property Alpdesk\AlpdeskFrontendediting\Listener\HooksListener::$currentPageId of type int` Nach dem Update auf den RC, egal ob ich die Funktion de- oder aktiviere.

**Comment by xprojects-de** [comment]
Servus,

danke fürs testen...

Kannst du mir mal einen StackTrace schicken bzw. den kompletten Fehlertext?

Danke und Grüße

**Comment by xprojects-de** [comment]
Servus,

habs gefunden. Da hat ein typecast gefehlt! Ist unter MariaDB und MySQL anders :-) Deswegen ist es nicht immer aufgefallen.
Sollte jetzt aber in der 1.3.1 gefixt sein.

Grüße
