### ISSUE TITLE
parseFrontendTemplate Hook fügt jedem Newslistenelement einen Wrapper mit 10px Margin Top hinzu

### ISSUE THREAD

**Issue by theDyingMountain** [xprojects-de/alpdesk-frontendediting#89]
Das sorgt für eine fehlerhafte Anzeige im Frontend.

siehe https://github.com/xprojects-de/alpdesk-frontendediting/blob/a8537cd1d0a1637f471f4c615fe61e12b743bbbd/src/Listener/HooksListener.php#L382

**Comment by xprojects-de** [comment]
Jip, ist bekannt. Bei bestimmten Layouts war/ist dann das Parent-Module nicht mehr klickbar.
Denke aber man kann das entfernen! => see and text https://github.com/xprojects-de/alpdesk-frontendediting/releases/tag/1.3.0-RC0

**Comment by xprojects-de** [comment]
fixed in 1.3.1
